### ISSUE TITLE
[Forge] - Netherite Trident is held oddly.

### ISSUE THREAD

**Issue by AmyMialee** [OroArmor/Netherite-Plus-Mod#99] opened 2021-03-30 16:13 UTC
**Describe the bug**
Netherite Trident is held weirdly.
Only present in forge. (1.4.2)

**To Reproduce**
Hold a Netherite Trident.

**Expected behaviour**
It would be held normally.

**Screenshots**
![2021-03-30_17 09 53](https://user-images.githubusercontent.com/10999535/113020988-0a047000-917b-11eb-9255-3f97d0e35b4d.png)
![2021-03-30_17 09 52](https://user-images.githubusercontent.com/10999535/113020994-0b359d00-917b-11eb-839f-9069e8402330.png)
![2021-03-30_17 09 40](https://user-images.githubusercontent.com/10999535/113021007-0e308d80-917b-11eb-9d6e-4d7cc4bf99ad.png)
![2021-03-30_17 09 42](https://user-images.githubusercontent.com/10999535/113021011-0ec92400-917b-11eb-8232-87556acbf75d.png)

**Comment by OroArmor** [comment] 2021-03-30 17:47
Duplicate of #82

**Closed by OroArmor** 2021-03-30 17:47 UTC
Labels: bug
